default: &default
  adapter: postgresql
  encoding: unicode
  pool: 200 # Follow GoodJob's recommendation

development:
  <<: *default
  url: postgres://scoutvol@localhost:5432/scoutvol_development

test:
  <<: *default
  url: postgres://scoutvol@localhost:5432/scoutvol_test

production:
  primary: &primary_production
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    adapter: sqlite3
    database: scoutvol_production_cache
    migrations_paths: db/cache_migrate
  cable:
    adapter: sqlite3
    database: scoutvol_production_cable
    migrations_paths: db/cable_migrate
